# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'position_readout_for_AM3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(436, 196)
        self.readout = QtWidgets.QWidget(MainWindow)
        self.readout.setObjectName("readout")
        self.gridLayout = QtWidgets.QGridLayout(self.readout)
        self.gridLayout.setObjectName("gridLayout")
        self.readout_box = QtWidgets.QGroupBox(self.readout)
        self.readout_box.setObjectName("readout_box")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.readout_box)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.begin_button = QtWidgets.QPushButton(self.readout_box)
        self.begin_button.setObjectName("begin_button")
        self.gridLayout_2.addWidget(self.begin_button, 1, 0, 1, 1)
        self.readout_display = QtWidgets.QLCDNumber(self.readout_box)
        self.readout_display.setObjectName("readout_display")
        self.gridLayout_2.addWidget(self.readout_display, 0, 0, 1, 2)
        self.zero_button = QtWidgets.QPushButton(self.readout_box)
        self.zero_button.setObjectName("zero_button")
        self.gridLayout_2.addWidget(self.zero_button, 1, 1, 1, 1)
        self.direction_button = QtWidgets.QPushButton(self.readout_box)
        self.direction_button.setObjectName("direction_button")
        self.gridLayout_2.addWidget(self.direction_button, 2, 0, 1, 1)
        self.direction_label = QtWidgets.QLabel(self.readout_box)
        self.direction_label.setObjectName("direction_label")
        self.gridLayout_2.addWidget(self.direction_label, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.readout_box, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.readout)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 436, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "POSITION READOUT"))
        self.readout_box.setTitle(_translate("MainWindow", "Position Redout in Meters"))
        self.begin_button.setText(_translate("MainWindow", "Begin Position Display"))
        self.zero_button.setText(_translate("MainWindow", "Set Current Position As Zero"))
        self.direction_button.setText(_translate("MainWindow", "Set Direction"))
        self.direction_label.setText(_translate("MainWindow", "Current Direction: Clockwise"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
